'use strict';
// tests/modules/test-nexstore-census.test.js — N0 of docs/2026-09-29-nex-node-store-phasemap.spec (0.39.300), the phase
// intelligence's gap synthesis ranked first (it unblocks twelve phases of the node store).
// The map's proof: "every JaaStore table and every nodes directory found in the tree appears in the catalogue with a kind
// (no unclassified data shape)".
//
//   NC-01  on the real tree: an independent walk finds every table (a .json of rows under a data/ dir) and every
//          nodes/<type>/ directory — each is in the census with one of the map's seven kinds; none unclassified
//   NC-02  the kinds: edge (two ends), lattice, ledger (a log, a .jsonl), snapshot, ring, record (an identity); a table
//          that fits none is a gap, listed, never forced; undeclared node types are named
//   NC-03  the catalogue: docs/nexstore-type-catalogue.yaml is valid YAML, generated by the census, every type with a kind
require('../../lib/test-sandbox.js').ensure();
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const yaml = require('js-yaml');

const ROOT = path.join(__dirname, '../..');
const C = require(path.join(ROOT, 'lib/nexstore/census.js'));
let passed = 0, failed = 0;
function test(id, name, fn) {
  try { fn(); console.log(`  ✓ ${id} ${name}`); passed++; }
  catch (e) { console.error(`  ✗ ${id} ${name}\n    ${e.stack}`); failed++; }
}

const census = C.census({ root: ROOT });

test('NC-01', 'every table and every nodes directory in the tree is catalogued with a kind', () => {
  const SKIP = /(^|\/)(node_modules|\.git|_archive|archive|unintegrated|dist|fixtures|output|projects)(\/|$)/;
  const tables = [], nodeDirs = [];
  (function walk(dir, depth) {
    if (depth > 9) return;
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name), r = path.relative(ROOT, p).split(path.sep).join('/');
      if (SKIP.test(r)) continue;
      if (e.isDirectory()) { if (path.basename(path.dirname(p)) === 'nodes' && e.name !== '_archive') { nodeDirs.push(r); continue; } walk(p, depth + 1); continue; }
      if (!/(^|\/)data\//.test(r) || !/\.json$/.test(e.name)) continue;
      let j; try { j = JSON.parse(fs.readFileSync(p, 'utf8')); } catch (_) { continue; }
      if (C.rowsOf(j)) tables.push(r);
    }
  })(ROOT, 0);
  assert.ok(tables.length >= 10 && nodeDirs.length >= 5, `the walk found tables and node dirs (${tables.length}, ${nodeDirs.length})`);
  for (const t of tables) {
    const hit = census.types.find(x => x.source === t);
    assert.ok(hit, `table ${t} is in the catalogue`); assert.ok(C.KINDS.includes(hit.kind), `${t} has a kind (${hit.kind})`);
  }
  for (const d of nodeDirs) {
    const hit = census.types.find(x => x.name === `node.${path.basename(d)}` && (x.dirs || []).includes(d));
    assert.ok(hit && C.KINDS.includes(hit.kind), `nodes dir ${d} is catalogued with a kind`);
  }
  assert.deepStrictEqual(census.gaps, [], 'no unclassified data shape in the tree');
  assert.ok(census.stats.knownTypes >= 50 && census.stats.schemas >= 50, 'the declared types and schemas are read');
  assert.ok(census.types.some(t => t.kind === 'snapshot' && t.store === '.nex'), 'versionium\'s .nex snapshots');
  assert.ok(census.types.some(t => t.kind === 'ring' && /rfr2|kernel|Stream/.test(t.source)), 'rings declared in code');
});

test('NC-02', 'the kinds; a misfit is a gap; undeclared node types are named', () => {
  assert.strictEqual(C.kindOf({ name: 'links', fields: ['fromUuid', 'toUuid'] }), 'edge');
  assert.strictEqual(C.kindOf({ name: 'cfr_tension_history', fields: ['ts'] }), 'lattice');
  assert.strictEqual(C.kindOf({ name: 'event_log', fields: ['ts', 'type'] }), 'ledger');
  assert.strictEqual(C.kindOf({ name: 'x', fields: [], file: 'x.jsonl' }), 'ledger');
  assert.strictEqual(C.kindOf({ name: 'backup_records', fields: ['id'] }), 'snapshot');
  assert.strictEqual(C.kindOf({ name: 'ideas', fields: ['uuid', 'text'] }), 'record');
  assert.strictEqual(C.kindOf({ name: 'blobby', fields: ['colour', 'size'] }), null, 'no identity, no ends, no stamp: no kind');
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'census-'));
  fs.mkdirSync(path.join(root, 'sys/data/nodes/thing'), { recursive: true });
  fs.writeFileSync(path.join(root, 'sys/data/nodes/thing/a.thing'), 'x');
  fs.writeFileSync(path.join(root, 'sys/data/blobby.json'), JSON.stringify([{ colour: 'red', size: 2 }]));
  fs.writeFileSync(path.join(root, 'sys/data/ideas.json'), JSON.stringify([{ uuid: 'u1', ideaUuid: 'u0' }]));
  const c = C.census({ root });
  assert.deepStrictEqual(c.gaps.map(g => g.type), ['sys.blobby'], 'the misfit is listed, never forced');
  assert.deepStrictEqual(c.types.find(t => t.name === 'sys.ideas').references, ['ideaUuid'], 'references read');
  assert.deepStrictEqual(c.undeclared.map(u => u.type), ['thing'], 'a node type lib/node-export.js does not declare is named');
});

test('NC-03', 'the catalogue: generated, valid YAML, every type with a kind', () => {
  const text = fs.readFileSync(path.join(ROOT, 'docs/nexstore-type-catalogue.yaml'), 'utf8');
  const doc = yaml.load(text);
  assert.match(doc.catalogue.generatedBy, /lib\/nexstore\/census\.js/);
  assert.ok(doc.types.length >= 150, `${doc.types.length} types`);
  assert.ok(doc.types.every(t => C.KINDS.includes(t.kind)), 'every catalogued type has one of the seven kinds');
  assert.ok(Array.isArray(doc.gaps) && Array.isArray(doc.undeclared));
});

console.log(`\n  ${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
