# Idea to spec — made in the spec workshop (idearium)
# Written 2026-10-10 from the phasemaps, to be opened in the workshop (nexus/idearium → its spec folder) and built through
# Idearium's own loop. Every block carries its decisions as choices — [A] [B] [C] and [custom] — with the coder's
# recommendation marked; "chosen:" stays "open" until James picks. Nothing here is built yet.
spec:
  name: Idea to spec
  ambition: 3 — outside the box
  source: "maps: docs/2026-10-10-idearium-solid-phasemap.spec SD6 SD7 SD10 SD12 SD14 · docs/2026-10-10-design-surface-phasemap.spec DS6"
  owner: idearium (the workshop, the void, the spec engine) · core (lib/spec-document.js, lib/chunker) · copilot (the one route every agent call takes)
  status: specced 2026-10-10, not built
  james: >-
    "like i feel idearium, when speccing, needs top start with the idea, map the primitives or invariants or principles,
    then the dependancies are built from there" · "trying to make the spec blocks as dumb as possible" · "the gap from
    idea to a complete spec in the workshop, is getting them to automatically use the primitives or something to
    understand what kind of structure it needs. Like the dependancy graph. Can you populate each block section with full
    multiple choice options with a custom option. Like the idea expansion in idearium is important."
sections:
  - id: purpose
    title: Purpose
    body: |
      Close the gap between one line of an idea and a complete spec Idearium can build from — in any domain.

      Today the workshop has the parts (ambition dial, feeds, templates, proposals he accepts) but nothing understands the
      idea's STRUCTURE: blocks are a list of eleven headings, only one dependency is declared (registry ← build_order),
      the void's echoes are one-shot (each sees only the idea, never the conversation), and an empty block is either
      written by hand or filled by one prompt with no sense of what it must be built from.

      After this: an idea is a thread (logged, asked, expanded). Its primitives are found first — the things, rules,
      actions, boundaries and modules it is made of, each with what is always true of it. Relations between them form a
      DAG. Every other block is a view computed from that graph, filled in dependency order, and every block that has a
      decision in it offers that decision as choices — several real options, each with what it costs, plus his own —
      so he steers by picking, not by writing prose. Each generated block passes an adversary before it is offered.

      The person stays the idea generator: nothing enters the spec without his yes.

  - id: primitives
    title: Primitives
    body: |
      The nouns of this feature itself — the spec eats its own dog food.

      thread      (thing)    an idea's conversation: turns {at, who, kind: log|ask|answer|expand|keep|drop, text, cites[]}
                             invariant: append-only; a turn is never edited, a correction is a new turn
      node        (thing)    one primitive of a spec: {id, kind, name, invariants[], body, source}
                             invariant: id unique in the spec; kind ∈ thing | rule | action | boundary | module
      relation    (thing)    {from, verb, to, known} — verb ∈ contains | uses | produces | constrains | exposes
                             invariant: known ∈ stated | rule | proposed | observed; only stated + rule drive anything
      view        (action)   a familiar block (schema, api, events, tests, build_order …) computed from nodes + relations
                             invariant: a view never holds a fact a node does not; it can be regenerated byte-for-byte
      choice      (thing)    a decision inside a block: {id, question, options[{key, label, says, costs, recommended}], custom, chosen}
                             invariant: always has a custom option; "chosen" is his or "open", never the agent's
      callto      (rule)     how an empty block is made: {file_tree} | {agent: <brief>} | {from: <block>} | {view: <name>}
                             invariant: a callto runs only when every block it reads from is non-empty
      gate verdict (thing)   {attacks[], confidence 0–1, reasons, by, against[]} — SD10's output, kept with the block
                             invariant: a confidence is never shown without its reasons
      generation run (action) fills the empty blocks of one spec in DAG order, one proposal each, each gated

      chosen: open — the five kinds and five verbs are the coder's proposal (SD12 revised); see the choice below.

      choices — the kinds of primitive (one is needed before anything else is built):
        [A] five kinds: thing · rule · action · boundary · module  ← recommended (small, covers data, invariants, processes, interfaces, nesting)
        [B] three kinds: entity · rule · flow — fewer to learn; boundaries become entities with a flag, modules become tags
        [C] open kinds: any word he types becomes a kind; the views learn which kinds they read
        [custom] ____

  - id: axioms
    title: Axioms
    body: |
      AX1  He is the idea generator. An agent proposes; nothing reaches a block, a node or a choice until he accepts it.
      AX2  Domain-agnostic. Nothing assumes code: a song's schema is its sections and keys, a game's its entities and rules.
      AX3  Every generated thing cites what it came from (a thread turn, a node, a block). No source → no content: an empty
           input yields an empty block, never invented filler (SD7's pushback, his "confident filler").
      AX4  The graph is the truth; blocks are views. A view is never edited into disagreeing with the graph — editing a
           view edits the nodes it shows.
      AX5  A decision is a choice, not prose. Where a block holds a decision, the options are listed with their costs, and
           a custom option is always present.
      AX6  Only stated and rule relations drive generation, staleness and build order. Proposed and observed relations are
           shown, never built from (RFR2's known-ness, revised_2).
      AX7  A cycle among driving relations is refused, with both ends named.
      AX8  Existing specs are read as they are and converted only on request — never in place, the original kept (§0.3).
      AX9  Nothing silently fails (§1.2): a generation that did not run says why; a gate that could not reach an adversary
           says so and falls back to the heuristic floor, labelled as such.

  - id: schema
    title: Schema
    body: |
      Where each primitive lives (each system owns its own data — architecture-spec NODE_SYSTEM):

      thread        idearium jaa table idearium_idea_threads, one row per turn, keyed by idea uuid (void.js extended)
      nodes,
      relations     inside the spec file itself, as two new section kinds the workshop reads and writes:
                      - id: nodes      body: one node per line group (id · kind · name · invariants · body)
                      - id: relations  body: one relation per line: "<from> <verb> <to> [<known>]"
                    so the file stays the truth (lib/spec-document.js's rule) and a person can read it as text
      choices       inside the block's body, in the plain-text form used throughout this file:
                      choices — <question>:
                        [A] <label>: <says> — <costs>   ← recommended
                        [custom] ____
                      chosen: open | A | custom: <his words>
                    (plain text survives the workshop's load/save, which keeps only id · title · body)
      verdicts      idearium jaa table idearium_gate_verdicts {spec, block, hash, attacks, confidence, reasons, by, at}
      runs          idearium jaa table idearium_generation_runs {spec, order[], per block: state, proposal, verdict}

      choices — where nodes and relations are kept:
        [A] in the spec file, as two sections (above)  ← recommended (the file is the truth; diffable; versioned by versionium)
        [B] in a jaa table, the file holding only the views — faster queries, but the file stops being the truth
        [C] a sidecar file beside the spec (<name>.graph.yaml) — clean, but two files to keep in step
        [custom] ____
      chosen: open

  - id: api
    title: API
    body: |
      Backend first, then routes, then commands, then screens (his order).

      Thread (SD6)
        POST /api/ideas/:uuid/thread        { kind: log|ask|expand, text }   → the new turn(s); ask/expand reach an agent
                                             through copilot with the WHOLE thread + repo/library context
        GET  /api/ideas/:uuid/thread                                          → every turn
        POST /api/ideas/:uuid/thread/:turn/keep | drop                        → his verdict on one expand part
      Primitives and relations (SD12)
        POST /api/workshop/:uuid/primitives/find      → proposals: nodes + relations from the purpose and the thread
        POST /api/workshop/:uuid/nodes                { add | edit | remove }
        POST /api/workshop/:uuid/relations            { add | remove }  — a cycle is a 409 naming both ends
        GET  /api/workshop/:uuid/graph                → nodes, relations, the DAG order, problems
      Views (SD12)
        GET  /api/workshop/:uuid/views/:name          → the block computed from the graph (schema, api, events, tests, build_order)
      Choices (new, CH)
        POST /api/workshop/:uuid/blocks/:id/choices   → proposals: the decisions in this block, each with 3–5 options + custom
        POST /api/workshop/:uuid/blocks/:id/choose    { choice, key | custom }  → recorded as his; dependents marked stale
      Generation (SD7) and gate (SD10)
        POST /api/workshop/:uuid/generate             { blocks?: [...], gate: on|sampled|off } → a run; fills in DAG order
        GET  /api/workshop/:uuid/runs/:run            → per block: waiting · generating · gated · offered · accepted
        POST /api/gate                                { output, purpose, sources[] } → verdict (any system may call it)
      Commands (route-commands rows; agents get them through nexus.command)
        idearium idea log|ask|expand <idea> <text> · idea thread <idea>
        idearium spec primitives <workshop> · spec graph <workshop> · spec choose <workshop> <block> <choice> <key>
        idearium spec generate <workshop> [--gate sampled]

      choices — how choices are produced for a block:
        [A] on demand: a "choices" button per block, one agent call  ← recommended (he pays only for the blocks he wants opened)
        [B] always: every block gets choices when it is generated — richer, ~2× the agent calls
        [C] only where the gate finds an undecided point ("open loop") — fewest calls, may miss decisions he cares about
        [custom] ____
      chosen: open

  - id: events
    title: Events
    body: |
      idearium.idea.turn          { idea, turn, kind, by }
      idearium.spec.node          { workshop, node, act: added|edited|removed }
      idearium.spec.relation      { workshop, from, verb, to, known, act }
      idearium.spec.choice        { workshop, block, choice, key|custom, by }
      idearium.spec.generated     { workshop, run, block, verdict: pass|flag|regenerated }
      idearium.gate.verdict       { subject, confidence, attacks: n, by }  (also teaches the learned order, SD10)
      Each declared in idearium/event-taxonomy.cjs before it is emitted (EC-05 holds the contract).

  - id: integration
    title: Integration
    body: |
      - the void (idearium/lib/void.js): an echo becomes a thread turn; "expand" in the void is the same expand
      - the workshop: two new sections (nodes, relations), the views shown as the familiar blocks, a choices strip on any
        block with a decision; FEEDS stay (open loops, what-ifs, d20 …) and now cite the nodes they touch
      - the spec engine (blocks.yaml): each block declares what it is built from — schema ← primitives + axioms;
        api, events ← schema; integration ← api + events; failure_modes ← axioms + integration; build_order ← all;
        tests ← axioms + schema + api; registry ← build_order (staleness already spreads along depends_on, HP1)
      - lib/spec-document.js: the nodes and relations sections parsed like any section (byte-for-byte kept)
      - the chunker (SD14): a build chunk is a node plus the nodes its stated relations reach, cut at the model's budget,
        naming what did not fit
      - the gate (SD10): lib/draft-review.js's author ≠ reviewer pairing, through the copilot route, never a fifth router
      - language routing (docs/language-routing.spec): a module node may name its language; the skeleton comes from its glyph

      choices — who writes the first primitives:
        [A] the agent proposes them from the purpose + thread; he keeps, edits or drops each  ← recommended
        [B] he lists them himself; the agent only checks for missing or contradicting ones (MANUAL mode)
        [C] deterministic first: nouns and verbs extracted from his text, the agent only names kinds
        [custom] ____
      chosen: open

  - id: failure_modes
    title: Failure modes
    body: |
      F1  Confident filler — a generated block reads well and says nothing. → AX3 (cite or stay empty) + the gate's attacks.
      F2  Relation noise — too many verbs, every node related to every other. → five verbs; observed relations never drive.
      F3  A cycle — two blocks each built from the other. → refused at write, both ends named (AX7).
      F4  The adversary is down or rate-limited. → verdict "unchecked" with the heuristic floor, labelled; never "pass".
      F5  Cost — 30 blocks × (writer + adversary) through the economy. → gate modes (on · sampled · off) and on-demand choices.
      F6  An old spec without nodes. → read as today; "convert" builds nodes from its blocks as proposals (AX8).
      F7  A choice the agent quietly decides. → "chosen" can only be written by a person's route (personOnly on the command).
      F8  The views drift from the graph after a hand edit. → editing a view edits the nodes; a view is regenerated, never patched.

  - id: build_order
    title: Build order
    body: |
      1  SD6  the thread — log / ask / expand with the whole conversation (backend → route → command → void UI)
      2  CH   choices in a block — parse/write the plain-text form, the choose route, the strip in the workshop
      3  SD12 nodes + relations sections, the graph route, cycle refusal, blocks.yaml dependencies
      4  SD12 views computed from the graph (schema, api/events, tests, build_order)
      5  SD10 the gate — one function any system calls; verdicts kept and taught to the learned order
      6  SD7  generation — callto per block, DAG order, every output through the gate, offered as a proposal
      7  SD14 chunks cut at primitives
      Each step is one phase, proven by its test before the next starts. 2 can ship before 3: choices are useful on
      today's blocks.

      choices — what to build first:
        [A] the thread (SD6), then choices — the conversation is what everything later cites  ← recommended
        [B] choices first — the fastest visible change in the workshop
        [C] primitives first — the structural core, but nothing to cite yet
        [custom] ____
      chosen: open

  - id: tests
    title: Tests
    body: |
      T1  thread: log an idea, ask twice, expand once → the second answer quotes the first; all turns on disk; a turn cannot be edited
      T2  choices: a block with "choices — …" round-trips through workshop load/save byte-for-byte; "chosen" refuses an agent caller
      T3  graph: a relation that closes a cycle → 409 naming both ends; proposed/observed relations do not change build order
      T4  views: schema regenerated from nodes is byte-identical twice; changing one node marks schema, api and tests stale
      T5  gate: a filler block (claims, no sources) is flagged with attacks and a low score; a grounded block passes; no adversary → "unchecked"
      T6  generation: from purpose + thread alone, empty blocks fill in DAG order, each citing its source and carrying its verdict
      T7  chunks: a 12-node spec builds in chunks of one node + its related nodes; a small model's chunk names what did not fit
      T8  domain: the same flow on a non-code idea (a song) produces a schema of sections and keys, not tables
      Clear Glass probe for the workshop screens (never Playwright).

  - id: registry
    title: Registry
    body: |
      idearium.idea-thread (idearium/lib/idea-thread.js) · idearium.spec-graph (idearium/lib/spec-graph.js) ·
      idearium.spec-views (idearium/lib/spec-views.js) · idearium.choices (idearium/lib/choices.js) ·
      core.gate (lib/gate.js) · idearium.generation (idearium/lib/generation.js)
      Each wired into loom with its real consumer edges (loom/maps/build-surface-map.js), each in docs/nexstore-writers.yaml
      for every table it writes.
