'use strict';
/**
 * nexus-healer/api/index.js — generated by loom/templates/system-scaffold.js
 * dispatch() is the single source both CLI and API call — one place to
 * implement real behavior, not two surfaces that quietly diverge.
 * Routes below are ordered longest-path-first — see comment in the
 * generator (system-scaffold.js) for why that ordering is load-bearing.
 * Route matching is real segment matching, not startsWith() — a :param
 * segment matches any value there and is extracted into args.
 */
const http = require('http');
const { URL } = require('url');
const fs = require('fs');
const path = require('path');

const PORT = parseInt(process.env.NEXUS_HEALER_PORT || '3755', 10);

function _matchPath(pattern, pathname, paramNames, args) {
  const patSegs = pattern.split('/').filter(Boolean);
  const reqSegs = pathname.split('/').filter(Boolean);
  if (reqSegs.length < patSegs.length) return false;
  for (let i = 0; i < patSegs.length; i++) {
    if (patSegs[i].startsWith(':')) {
      args[patSegs[i].slice(1)] = reqSegs[i];
    } else if (patSegs[i] !== reqSegs[i]) {
      return false;
    }
  }
  return true;
}

// §BUILT 2026-07-14 — real propose/list/evaluate, replacing the generated
// stubs. Deliberately scoped: merge/archive stay stubs — actually
// committing a change (or explicit, permanent archival) is real, separate
// work, not rushed into the same turn that wired hypothesis generation.
const { jaaDB } = require('../../cortex/memory/jaa-db.js');

async function dispatch(opId, args) {
  switch (opId) {
    case 'propose': {
      if (!args.text) return { ok: false, error: 'text is required' };
      const proposal = {
        uuid: require('crypto').randomUUID(),
        text: args.text,
        causedBy: args.causedBy || null,
        status: 'proposed',
        ts: Date.now(),
      };
      try { jaaDB.insert('healer_proposals', proposal); }
      catch (e) { return { ok: false, error: `could not record proposal: ${e.message}` }; }
      return { ok: true, proposalId: proposal.uuid, status: proposal.status };
    }

    case 'list': {
      let rows;
      try { rows = jaaDB.query('healer_proposals', {}); }
      catch (e) { return { ok: false, error: `could not list proposals: ${e.message}` }; }
      return { ok: true, count: rows.length, proposals: rows };
    }

    case 'evaluate': {
      if (!args.id) return { ok: false, error: 'id is required' };
      if (!args.targetFile) return { ok: false, error: 'targetFile is required — evaluate needs a real file to propose a patch against' };

      const proposal = jaaDB.get('healer_proposals', { uuid: args.id });
      if (!proposal) return { ok: false, error: `no proposal found with id ${args.id}` };

      // §REAL PATH ONLY — read the actual current file, never a guess or
      // a cached copy. A proposal targeting a file that doesn't exist is
      // an honest error, not a fabricated "patch."
      const fullPath = path.join(process.env.NEXUS_ROOT || path.join(__dirname, '..', '..'), args.targetFile);
      let moduleSrc;
      try { moduleSrc = fs.readFileSync(fullPath, 'utf8'); }
      catch (e) { return { ok: false, error: `could not read targetFile "${args.targetFile}": ${e.message}` }; }

      // forge now routes through Guardian/RAID (LAW_I) — see
      // meta/rfr2/forge/index.js's own §FIXED note. This call never
      // decides a provider itself.
      // §FIX 2026-07-24 — was meta/causal-nexus/modules/forge/index.js.
      // Migrated to meta/rfr2/forge (harvested + converted to real CJS
      // same session, rfr2.spec Job 2b) — rfr2 is the decided-canonical
      // tree (2026-07-21 audit), causal-nexus is the near-dead ancestor.
      // Functionally identical (harvested verbatim, only the module
      // system changed), so this is a path update, not a behavior change.
      let forge;
      try { forge = require('../../intelligence/rfr2/forge/index.js'); }
      catch (e) { return { ok: false, error: `forge module unavailable: ${e.message}` }; }

      let rec;
      try {
        rec = await forge.forgePatch(moduleSrc, { instruction: proposal.text }, { moduleName: args.targetFile });
      } catch (e) {
        return { ok: false, error: `forge dispatch failed: ${e.message}` };
      }
      if (rec.error) {
        jaaDB.update('healer_proposals', { uuid: args.id }, { status: 'generation-failed', generationError: rec.error.message || String(rec.error) });
        return { ok: false, error: `forge could not generate a patch: ${rec.error.message || rec.error}` };
      }

      // §HONEST STATUS — 'generated', not 'passed'. This turn wires real
      // hypothesis generation; it does not yet fork the repo, apply the
      // patch, or run real tests against it (the next real stage).
      // Claiming 'passed' here would be exactly the kind of overclaim
      // this whole session has been correcting elsewhere.
      jaaDB.update('healer_proposals', { uuid: args.id }, {
        status: 'generated', targetFile: args.targetFile, generatedSrc: rec.src,
        hooksDelta: rec.hooksDelta, forgeProvider: rec.provider || 'unknown',
        forgeDurationMs: rec.durationMs, evaluatedAt: Date.now(),
      });
      return {
        ok: true, proposalId: args.id, status: 'generated',
        targetFile: args.targetFile, generatedSrc: rec.src,
        note: 'real code generated via forge (RAID-routed); not yet fork-tested or merged — that is the next real stage',
      };
    }

    case 'merge': return { ok: true, op: 'merge', args, note: 'stub handler — replace with real logic' };
    case 'archive': return { ok: true, op: 'archive', args, note: 'stub handler — replace with real logic' };
    default: return { ok: false, error: `unknown operation: ${opId}` };
  }
}

// §FIXED 2026-07-14 — found while wiring nexus-healer's real propose/
// evaluate logic, not hypothetical: args was built ONLY from URL search
// params, every single POST body was silently ignored. Every scaffolded
// system with a create/action-style POST endpoint (propose a healer
// hypothesis, submit anything with a real payload) had this same gap —
// same root-cause shape as the real bug found in cortex/boot.js's
// POST /api/recall earlier this session (query never read from the
// body). Fixed at the generator, not just nexus-healer's one file, so
// every future scaffolded system gets this for free.
function _readBody(req) {
  return new Promise((resolve) => {
    if (req.method !== 'POST' && req.method !== 'PUT' && req.method !== 'PATCH') { resolve({}); return; }
    let data = '';
    req.on('data', c => data += c);
    req.on('end', () => { try { resolve(JSON.parse(data || '{}')); } catch (_) { resolve({}); } });
    req.on('error', () => resolve({}));
  });
}

function createServer() {
  return http.createServer(async (req, res) => {
    const u = new URL(req.url, `http://${req.headers.host || 'localhost'}`);
    const body = await _readBody(req);
    const args = { ...Object.fromEntries(u.searchParams), ...body };
  if (req.method === 'POST' && _matchPath('/proposals/:id/evaluate', u.pathname, ["id"], args)) {
    const result = await dispatch('evaluate', args);
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(result));
    return;
  }
  if (req.method === 'POST' && _matchPath('/proposals/:id/archive', u.pathname, ["id"], args)) {
    const result = await dispatch('archive', args);
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(result));
    return;
  }
  if (req.method === 'POST' && _matchPath('/proposals/:id/merge', u.pathname, ["id"], args)) {
    const result = await dispatch('merge', args);
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(result));
    return;
  }
  if (req.method === 'POST' && _matchPath('/proposals', u.pathname, [], args)) {
    const result = await dispatch('propose', args);
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(result));
    return;
  }
  if (req.method === 'GET' && _matchPath('/proposals', u.pathname, [], args)) {
    const result = await dispatch('list', args);
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(result));
    return;
  }
    res.writeHead(404, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok: false, error: 'no matching route' }));
  });
}

if (require.main === module) {
  createServer().listen(PORT, () => console.log(`nexus-healer API on :${PORT}`));
}

module.exports = { dispatch, createServer, PORT };
