'use strict';
/**
 * nexus-healer/cli/index.js — generated by loom/templates/system-scaffold.js
 * Do not hand-edit the verb list below; regenerate from the operations
 * list instead, or CLI/API drift apart the way phase 64/hook-registry did.
 *
 * Usage: node nexus-healer/cli/index.js <verb> [--key value ...]
 */
const { dispatch } = require('../api/index');

function _parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith('--')) {
      const key = argv[i].slice(2);
      const val = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[++i] : true;
      out[key] = val;
    }
  }
  return out;
}

async function main() {
  const [verb, ...rest] = process.argv.slice(2);
  const args = _parseArgs(rest);
  switch (verb) {
    case 'propose': {
      const result = await dispatch('propose', args);
      console.log(JSON.stringify(result, null, 2));
      break;
    }
    case 'list': {
      const result = await dispatch('list', args);
      console.log(JSON.stringify(result, null, 2));
      break;
    }
    case 'evaluate': {
      const result = await dispatch('evaluate', args);
      console.log(JSON.stringify(result, null, 2));
      break;
    }
    case 'merge': {
      const result = await dispatch('merge', args);
      console.log(JSON.stringify(result, null, 2));
      break;
    }
    case 'archive': {
      const result = await dispatch('archive', args);
      console.log(JSON.stringify(result, null, 2));
      break;
    }
    default:
      console.error(`Unknown verb: ${verb}`);
      console.error('Available: propose, list, evaluate, merge, archive');
      process.exit(1);
  }
}

if (require.main === module) main();
module.exports = { main };
