'use strict';
/**
 * intelligence/framework-builder.js — phase 4 of the intelligence
 * extraction, and the one genuinely NEW capability in it (not a
 * migration). James: "frameworks for co-pilot. Can say, hey nexus lets
 * create a framework... code injects small warp logic framework for
 * coding, uses chatgpt specific chunking, and a small list of commands
 * it can use to communicate with nexus."
 *
 * Real, checked before building (§8.6):
 * - WARP's actual primitives (warp/core/{Gate,Axiom,Stream}.js) read
 *   directly, not assumed — the generated skeleton uses their real,
 *   confirmed constructor signatures.
 * - No agent-specific chunker exists anywhere; lib/chunk-service.js is
 *   the one real, canonical, agent-AGNOSTIC chunker already built and
 *   tested this session. Reused directly rather than building a
 *   parallel "chatgpt chunker" — "agent-specific" is satisfied by
 *   tagging the real chunk_input/chunk_output events with agent, per
 *   lib/event-types.js's own design (agent is a field, never baked
 *   into a separate mechanism).
 * - The "small list of commands" is the real, already-registered tool
 *   list (lib/agent-tools/index.js's TOOLS map) — not a new,
 *   parallel vocabulary invented here.
 *
 * comp_id: nexus.intelligence.framework-builder
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const DROP_DIR = path.join(ROOT, 'intelligence', 'output');

/** realCommandVocabulary() — the actual, currently-registered tool list, not a fabricated one. */
function realCommandVocabulary() {
  try {
    const { TOOLS } = require('../lib/agent-tools/index.js');
    return [...TOOLS.keys()].sort();
  } catch (_) {
    return []; // §1.2 — an unreachable registry is an honest empty list, not a guessed one
  }
}

/** toPascalCase(safeName) — real, correct conversion; safeName is already [a-z0-9-] only. */
function toPascalCase(safeName) {
  let out = safeName
    .split('-')
    .filter(Boolean)
    .map(seg => seg.charAt(0).toUpperCase() + seg.slice(1))
    .join('');
  // §1.2 — a JS identifier can't start with a digit; a name like
  // "123-framework" would otherwise produce an invalid createXxx().
  if (/^[0-9]/.test(out)) out = 'F' + out;
  return out;
}

/** toCamelIdentifier(safeName) — real, safe const-variable name; same digit guard, prefixed lowercase, not PascalCase. */
function toCamelIdentifier(safeName) {
  const pascal = toPascalCase(safeName);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/**
 * buildSkeleton(name, opts) — generates a real, syntactically-correct
 * WARP-based module skeleton. Every construct in the output matches the
 * real API confirmed by reading warp/core/{Gate,Axiom,Stream}.js
 * directly: new Gate(signature, {matches, transform, schema}),
 * new Axiom(id, {check, severity}), new Stream({axioms}).register(gate).
 */
function buildSkeleton(name, opts = {}) {
  if (!name || typeof name !== 'string') throw new Error('buildSkeleton requires a real name');
  const safeName = name.replace(/[^a-z0-9-]/gi, '-').toLowerCase();
  const pascalName = toPascalCase(safeName);
  const gateVarName = toCamelIdentifier(safeName) + 'Gate';
  const agent = opts.agent || null;
  const description = opts.description || `Real WARP-based framework: ${name}`;
  const commands = realCommandVocabulary();

  const code = `'use strict';
/**
 * ${safeName}.js — ${description}
 * Generated by intelligence/framework-builder.js, ${new Date().toISOString()}
 * ${agent ? `Requested by agent: ${agent}` : ''}
 *
 * Real NEXUS command vocabulary available to this framework (the
 * currently-registered agent tools — call via lib/agent-tools/index.js's
 * executeTool(name, args)):
${commands.length ? commands.map(c => ` *   - ${c}`).join('\n') : ' *   (tool registry unreachable at generation time — check lib/agent-tools/index.js)'}
 *
 * For content too large for one pass, use the real, canonical chunker
 * rather than a custom splitter:
 *   const { chunkGoverned } = require('../../lib/chunk-service.js');
 *   const { chunks } = await chunkGoverned(bigContent, { agent: '${agent || 'unknown'}' });
 */
const { Gate, Axiom, Stream } = require('../../warp/core');

// ── Define the real invariant(s) this framework must never violate ────────
const noEmptyOutput = new Axiom('${safeName}.no-empty-output', {
  severity: 'hard',
  check: (event) => event && event.data != null,
});

// ── Define the real transform this framework performs ─────────────────────
// Real Event shape, confirmed by reading warp/core/Event.js directly:
// {type, data, uuid, ts}. transform(event) receives the RAW event passed
// to stream.emit(), and its return value is fed back through emit()
// recursively (warp/core/Stream.js's _emitProduced) — so returned events
// must be well-formed too: {type, data}.
const ${gateVarName} = new Gate('${safeName}.process', {
  transform(event) {
    // TODO: real transform logic goes here — this is a real, valid
    // starting point, not a finished implementation.
    return [{ type: '${safeName}.processed', data: event.data }];
  },
});

// ── Wire it into a real Stream ──────────────────────────────────────────
function create${pascalName}() {
  const stream = new Stream({ axioms: [noEmptyOutput] });
  stream.register(${gateVarName});
  return stream;
}

module.exports = { create${pascalName} };
`;

  return { code, safeName, description, agent };
}

/**
 * drop(name, opts) — writes a real skeleton to intelligence/output/, the
 * real, per-system result folder (matches lib/contract-queue.js's own
 * convention — every other system already has an input/output pair).
 * James: "also a physical folder so i can drag and drop." Dropping a real
 * request into intelligence/input/ (see intelligence/consumer.js) is the
 * input half; this is where the real, finished result lands. Creates the
 * directory if it doesn't exist yet.
 */
function drop(name, opts = {}) {
  const { code, safeName, description, agent } = buildSkeleton(name, opts);
  fs.mkdirSync(DROP_DIR, { recursive: true });
  const uuid = crypto.randomUUID();
  const outPath = path.join(DROP_DIR, `${safeName}-${uuid.slice(0, 8)}.js`);
  fs.writeFileSync(outPath, code, 'utf8');

  // Tags — James: "tags." A real, small sidecar, not embedded magic
  // comments a later reader would have to parse out of the code.
  const tagsPath = outPath.replace(/\.js$/, '.tags.json');
  fs.writeFileSync(tagsPath, JSON.stringify({
    name: safeName, description, agent, uuid, createdAt: Date.now(),
    tags: ['framework', 'warp', 'generated', ...(opts.tags || [])],
  }, null, 2), 'utf8');

  return { ok: true, outPath, tagsPath, uuid };
}

module.exports = { buildSkeleton, drop, realCommandVocabulary, DROP_DIR, MODULE_ID: 'intelligence.framework-builder', VERSION: '1.0.0' };
