'use strict';
/**
 * hooks/architect.hooks.js — Architect System Hook Map
 * UUID: architect-hooks-map-v1-0000-4000
 * System: Architect :3747
 */
const HOOKS = [
  { id:'arch-hook-register-0001', name:'architect-hook-register', intent:'DEPRECATED 2026-07-20 — hook registration moved to loom :3752 (docs/hooks-migration.spec). This endpoint returns 410 with a pointer to loom; kept for history, not a live capability.', type:'api', direction:'unidirectional', from:{surface:'*',layer:0}, to:{surface:'architect',layer:2,port:3747}, ui:{panel:'ARCHITECT > HOOKS', element:'+ Register Hook button, hook registration form', action:'POST /api/hooks — 410 Gone, use loom :3752'}, config:{path:'/api/hooks', method:'POST', validation:'§I-1 unique name, §I-2 schema, §I-4 no direct cross-layer'}, contract:{axioms:['§I-1','§I-2','§I-18','§A-2'], sideEffects:['jaa.insert("hooks")','emit architect.hook.registered'], idempotent:false}, references:{files:['architect/src/hooks/Registry.js → register()', 'hooks/index.js → seedArchitectRegistry()']}, seam:{componentId:'architect-hook-registration', intentId:'declare-wire-into-registry'}, status:'deprecated', supersededBy:'loom :3752 POST /api/hooks', updatedAt:'2026-08-11T00:00:00Z' },
  { id:'arch-hook-snr-0002', name:'architect-snr-gate', intent:'Score any JSON payload on 8 axes before routing to Ollama so signal always precedes noise', type:'snr', direction:'unidirectional', from:{surface:'*',layer:0}, to:{surface:'architect',layer:1,port:3747}, ui:{panel:'ARCHITECT > SNR GATE', element:'SNR score meter, 8-axis breakdown, routing recommendation', action:'POST /api/snr'}, config:{path:'/api/snr', axes:['structural','causal','constraint','gap','tension','vocabulary','temporal','behavioral'], thresholds:{send:0.85,hold:0.65,rewrite:0.45,flag:0}}, contract:{axioms:['§A-5','§I-6','§I-15'], sideEffects:['jaa.insert("snr_results")'], idempotent:true, snrGated:false}, references:{files:['architect/src/spec/Blueprint.js → SNRGate']}, seam:null, status:'active', updatedAt:'2026-06-11T17:30:00Z' },
  { id:'arch-hook-scan-0003', name:'architect-topology-scan', intent:'Scan a directory to build a file topology map so the team can see what exists before building what does not', type:'blueprint', direction:'unidirectional', from:{surface:'*',layer:0}, to:{surface:'architect',layer:3,port:3747}, ui:{panel:'ARCHITECT > BLUEPRINT + TOPOLOGY', element:'Path input + Scan button, file map with gap detection', action:'POST /api/blueprint/scan'}, config:{path:'/api/blueprint/scan', schema:'{ rootPath, opts? }', gapTypes:['missing-file','no-schema','missing-test','broken-import','undeclared-hook','orphaned-surface']}, contract:{axioms:['§A-3'], sideEffects:['jaa.insert("blueprints")','jaa.insert("topology_maps")'], idempotent:true}, references:{files:['architect/src/spec/Blueprint.js → scanTopology()']}, seam:null, status:'active', updatedAt:'2026-06-11T17:30:00Z' },
];
module.exports = { systemId:'architect', port:3747, version:'1.0.0', updatedAt:'2026-06-11T17:30:00Z', hooks:HOOKS, byId:(id)=>HOOKS.find(h=>h.id===id), byName:(n)=>HOOKS.find(h=>h.name===n), byType:(t)=>HOOKS.filter(h=>h.type===t), withSEAM:()=>HOOKS.filter(h=>h.seam!==null), active:()=>HOOKS.filter(h=>h.status==='active') };
