'use strict';
/**
 * hooks/cortex.hooks.js — Cortex System Hook Map
 * UUID: cortex-hooks-map-v1-0000-4000
 * Status: pre-release
 * System: Cortex :3748
 * Status: living
 */

const CORTEX_HOOKS = [
  {
    id: "cortex-hook-settings-js-0300",
    name: "cortex-settings-js",
    intent: "Alias of /api/settings, served under a .js path because the UI loads it as a script tag. Same handler.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/settings.js", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true, methodEnforced: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-cli-exec-get-0200",
    name: "cortex-api-cli-exec-get",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/cli/exec", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true, methodEnforced: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-events-get-0202",
    name: "cortex-api-events-get",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/events", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true, methodEnforced: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-failure-modes-get-0203",
    name: "cortex-api-failure-modes-get",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/failure-modes", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true, methodEnforced: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-friction-get-0204",
    name: "cortex-api-friction-get",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/friction", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true, methodEnforced: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-health-get-0205",
    name: "cortex-api-health-get",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/health", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true, methodEnforced: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-memory-forget-post-0213",
    name: "cortex-api-memory-forget-post",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/memory/forget", method: "POST" },
    contract: { axioms: [], sideEffects: [], idempotent: false, methodEnforced: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-memory-insert-post-0214",
    name: "cortex-api-memory-insert-post",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/memory/insert", method: "POST" },
    contract: { axioms: [], sideEffects: [], idempotent: false, methodEnforced: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-memory-working-post-0215",
    name: "cortex-api-memory-working-post",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/memory/working", method: "POST" },
    contract: { axioms: [], sideEffects: [], idempotent: false, methodEnforced: true },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-memory-working-get-0216",
    name: "cortex-api-memory-working-get",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/memory/working", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true, methodEnforced: true },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-meta-observe-post-0217",
    name: "cortex-api-meta-observe-post",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/meta/observe", method: "POST" },
    contract: { axioms: [], sideEffects: [], idempotent: false, methodEnforced: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-raid-health-get-0218",
    name: "cortex-api-raid-health-get",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/raid/health", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true, methodEnforced: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-replay-inspect-get-0219",
    name: "cortex-api-replay-inspect-get",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/replay/inspect", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true, methodEnforced: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-self-heal-status-get-0220",
    name: "cortex-api-self-heal-status-get",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/self-heal/status", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true, methodEnforced: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-settings-get-0221",
    name: "cortex-api-settings-get",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/settings", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true, methodEnforced: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-snapshots-post-0222",
    name: "cortex-api-snapshots-post",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/snapshots", method: "POST" },
    contract: { axioms: [], sideEffects: [], idempotent: false, methodEnforced: true },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-snapshots-get-0223",
    name: "cortex-api-snapshots-get",
    intent: "Declared from code (scripts/analyze-methodless-routes.js). methodEnforced=false means the handler has NO method guard: any verb reaches it.",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/snapshots", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true, methodEnforced: true },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-nerve-snapshot-get-0100",
    name: "cortex-nerve-snapshot-get",
    intent: "Read nerve snapshot (generated from code by scripts/generate-hooks.js — refine by hand)",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/nerve/snapshot", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-hooks-summary-get-0101",
    name: "cortex-hooks-summary-get",
    intent: "Read hooks summary (generated from code by scripts/generate-hooks.js — refine by hand)",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/hooks/summary", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-raid-feedback-post-0102",
    name: "cortex-api-raid-feedback-post",
    intent: "Write raid feedback (generated from code by scripts/generate-hooks.js — refine by hand)",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/raid/feedback", method: "POST" },
    contract: { axioms: [], sideEffects: [], idempotent: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-api-table-insert-post-0103",
    name: "cortex-api-table-insert-post",
    intent: "Write table insert (generated from code by scripts/generate-hooks.js — refine by hand)",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/table/insert", method: "POST" },
    contract: { axioms: [], sideEffects: [], idempotent: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-raid-decide-0015",
    name: "cortex-raid-decide",
    intent: "RAID provider selection over the API (AX-010) — replaces require(cortex/core/raid)",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/raid/decide", method: "POST" },
    contract: { axioms: [], sideEffects: [], idempotent: false },
    references: { files: ["cortex/core/raid/index.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-personas-0014",
    name: "cortex-personas",
    intent: "Read/write personality profiles — the sovereign API replacing copilot cross-system require",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/personas", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true },
    references: { files: ["cortex/personas.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-snapshot-rollback-0013",
    name: "cortex-snapshot-rollback",
    intent: "Restore CFR field state from a stored snapshot",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/snapshot/rollback", method: "POST" },
    contract: { axioms: [], sideEffects: [], idempotent: false },
    references: { files: ["cortex/boot.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-recall-0012",
    name: "cortex-recall",
    intent: "Recall from unified memory (lexical + recency scored)",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/recall", method: "GET" },
    contract: { axioms: [], sideEffects: [], idempotent: true },
    references: { files: ["cortex/push-recall.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: "cortex-hook-push-0011",
    name: "cortex-push",
    intent: "Push content into unified memory (tiered, tagged)",
    type: "api",
    direction: "unidirectional",
    from: { surface: "*", layer: 0 },
    to: { surface: "cortex", layer: 1, port: 3748 },
    config: { path: "/api/push", method: "POST" },
    contract: { axioms: [], sideEffects: [], idempotent: false },
    references: { files: ["cortex/push-recall.js"] },
    status: "active",
    updatedAt: "2026-07-09T00:00:00Z"
  },
  {
    id: 'cx-hook-event-ingest-0001', name: 'cortex-event-ingest',
    intent: 'Receive events from all systems and write them to JAA event_log so nothing is lost',
    type: 'api', direction: 'sink',
    from: { surface:'*', layer:0 }, to: { surface:'cortex', layer:1, port:3748 },
    ui: { panel:'CORTEX > EVENTS', element:'Event ledger rows', action:'POST /api/event' },
    config: { path:'/api/event', method:'POST', schema:'{ type, payload, source, causedBy?, ts }' },
    contract: { axioms:['§2.1','§1.2'], sideEffects:['jaa.insert("event_log")','sigma.record()','delta.record()'], idempotent:false, replayable:true },
    references: { files:['cortex/foundation/admin-server.js → POST /api/event'] },
    seam: null, status:'active', updatedAt:'2026-06-11T17:30:00Z',
  },
  {
    id: 'cx-hook-snapshot-create-0003', name: 'cortex-snapshot-create',
    intent: 'Archive full JAA table state to a .nex snapshot so the system can rewind to any prior state',
    type: 'api', direction: 'unidirectional',
    from: { surface:'orchestrator', layer:1 }, to: { surface:'cortex', layer:1 },
    ui: { panel:'CORTEX > SNAPSHOTS', element:'Snapshot list + Create button', action:'POST /api/snapshots/create' },
    config: { path:'/api/snapshots/create', method:'POST', schema:'{ message? }', returns:'{ ok, snapId }' },
    contract: { axioms:['§2.1','§2.3'], sideEffects:['writes .nex file to data/snapshots/','jaa.insert("versionium_commits")'], idempotent:false, replayable:false },
    references: { files:['cortex/snapshot/index.js','cortex/foundation/admin-server.js → POST /api/snapshots/create'] },
    seam: null, status:'active', updatedAt:'2026-06-11T17:30:00Z',
  },
  {
    id: 'cx-hook-snapshot-rollback-0004', name: 'cortex-snapshot-rollback',
    intent: 'Restore all JAA tables to a prior snapshot state — the rewind button',
    type: 'api', direction: 'unidirectional',
    from: { surface:'orchestrator', layer:1 }, to: { surface:'cortex', layer:1 },
    ui: { panel:'CORTEX > SNAPSHOTS', element:'⏪ Rewind button on each snapshot row', action:'POST /api/snapshots/rollback' },
    config: { path:'/api/snapshots/rollback', method:'POST', schema:'{ snapId, apply:true }', warning:'restores JAA tables only — files on disk unchanged' },
    contract: { axioms:['§2.1'], sideEffects:['replaces all JAA table contents'], idempotent:false, replayable:false },
    references: { files:['cortex/snapshot/index.js → rollback()'] },
    seam: null, status: 'planned', // §PLANNED 2026-07-09 — NOT implementable from the current snapshot. POST /api/snapshots/create (implemented today) stores per-table CONTENT HASHES for integrity, not the content itself, so there is nothing to restore from. A real rollback is rfr2/compress.snapshot()/restore() (Phase 27, System State VM), which is blocked on the absent meta/rfr2/kernel module. See docs/RFR2-KERNEL-CONTRACT.md. Declaring this 'active' would be a lie, updatedAt:'2026-06-11T17:30:00Z',
  },
  {
    id: 'cx-hook-jaa-memory-0005', name: 'cortex-jaa-memory-query',
    intent: 'Expose JAA table contents for browsing and search so the system is fully observable',
    type: 'api', direction: 'bidirectional',
    from: { surface:'*', layer:0 }, to: { surface:'cortex', layer:1 },
    ui: { panel:'CORTEX > MEMORY + CORTEX > TABLES', element:'Table selector, row browser, filter', action:'GET /api/memory?table=X&n=200' },
    config: { path:'/api/memory', queryParams:['table','n'], maxRows:500 },
    contract: { axioms:['§2.3'], sideEffects:[], idempotent:true },
    references: { files:['cortex/foundation/admin-server.js → GET /api/memory'] },
    seam: null, status:'active', updatedAt:'2026-06-11T17:30:00Z',
  },
  {
    id: 'cx-hook-gap-write-0006', name: 'cortex-gap-write',
    intent: 'Record a named gap in JAA so nothing is unnamed and all gaps are observable and actionable',
    type: 'api', direction: 'unidirectional',
    from: { surface:'*', layer:0 }, to: { surface:'cortex', layer:1 },
    ui: { panel:'CORTEX > GAPS', element:'Gap list with severity badges', action:'POST /api/gaps or event cortex.gap.found' },
    config: { path:'/api/gaps', method:'POST', schema:'{ type, severity, description, source, path?, body? }' },
    contract: { axioms:['§1.2','§F-GAP-01'], sideEffects:['jaa.insert("gaps")'], idempotent:false },
    references: { files:['cortex/foundation/admin-server.js → POST /api/gaps'] },
    seam: null, status:'active', updatedAt:'2026-06-11T17:30:00Z',
  },
];

module.exports = {
  systemId:'cortex', port:3748, version:'3.0.0', updatedAt:'2026-06-11T17:30:00Z', hooks:CORTEX_HOOKS,
  byId:(id)=>CORTEX_HOOKS.find(h=>h.id===id), byName:(n)=>CORTEX_HOOKS.find(h=>h.name===n),
  byType:(t)=>CORTEX_HOOKS.filter(h=>h.type===t), withSEAM:()=>CORTEX_HOOKS.filter(h=>h.seam!==null), active:()=>CORTEX_HOOKS.filter(h=>h.status==='active'),
};
