'use strict';
/**
 * hooks/idearium.hooks.js — Idearium System Hook Map
 * UUID: idearium-hooks-map-v1-0000-4000
 * System: Idearium :4800
 */
const HOOKS = [
  { id:'ide-hook-idea-create-0001', name:'idearium-idea-create', intent:'Create a new idea card in idearium so intent is captured before implementation begins', type:'api', direction:'unidirectional', from:{surface:'*',layer:0}, to:{surface:'idearium',layer:1,port:4800}, ui:{panel:'IDEARIUM > IDEAS', element:'+ NEW IDEA button, idea card form', action:'POST /api/ideas'}, config:{path:'/api/ideas', method:'POST'}, contract:{axioms:['§A-1','§2.1'], sideEffects:['jaa.insert("ideas")','emit idearium.idea.created'], idempotent:false}, references:{files:['idearium/api/index.js → POST /api/ideas']}, seam:null, status:'active', updatedAt:'2026-06-11T17:30:00Z' },
  { id:'ide-hook-spec-create-0002', name:'idearium-spec-from-idea', intent:'Promote an idea to a .spec so it enters the build pipeline via the spec-compiler', type:'api', direction:'unidirectional', from:{surface:'idearium',layer:1}, to:{surface:'spec-compiler',layer:1}, ui:{panel:'IDEARIUM > SPEC', element:'Build Spec button on idea card', action:'POST /api/ideas/:uuid/spec'}, config:{path:'/api/ideas/:uuid/spec', method:'POST'}, contract:{axioms:['§A-1','§A-3'], sideEffects:['emit idearium.spec.create'], idempotent:false}, references:{files:['idearium/api/index.js → POST /api/ideas/:uuid/spec']}, seam:{componentId:'idearium-spec-promotion', intentId:'promote-idea-to-spec-for-compiler'}, status:'active', updatedAt:'2026-06-11T17:30:00Z' },
  { id:'ide-hook-gap-0003', name:'idearium-gap', intent:'Record a gap from idearium tension analysis so it surfaces in cortex and self-heal can act on it', type:'event-bus', direction:'unidirectional', from:{surface:'idearium',layer:1}, to:{surface:'cortex',layer:1}, ui:{panel:'IDEARIUM > GAPS', element:'Gap list', action:'Auto on idearium.gap.found event'}, config:{eventType:'idearium.gap.found'}, contract:{axioms:['§1.2'], sideEffects:['_toCortex("cortex.gap.found")'], idempotent:false}, references:{files:['idearium/api/index.js']}, seam:null, status:'active', updatedAt:'2026-06-11T17:30:00Z' },
  { id:'ide-hook-copilot-wire-0004', name:'idearium-to-copilot', intent:'Stream every idearium event (idea created/updated/phased, spec created, gap opened) to copilot so idea/project/lattice activity is no longer invisible to it — closes §AX-008', type:'stream', direction:'unidirectional', from:{surface:'idearium',layer:1,port:4800}, to:{surface:'copilot',layer:1,port:3750}, ui:{panel:null, element:null, action:'Auto-connects on copilot boot, 4s after listen'}, config:{path:'/sse', method:'GET', protocol:'SSE (text/event-stream)', reconnect:'2s on close, 5s on error'}, contract:{axioms:['§AX-008'], sideEffects:['copilot._stream.push(event)','copilot broadcast copilot.stream.event'], idempotent:true, replayable:true}, references:{files:['copilot/server.js → _connectIdeariumStream()','idearium/index.js → _broadcast()']}, seam:{componentId:'idearium-copilot-bridge', intentId:'close-ax008-idearium-visibility'}, status:'active', updatedAt:'2026-06-29T00:00:00Z' },
];
module.exports = { systemId:'idearium', port:4800, version:'1.0.0', updatedAt:'2026-06-11T17:30:00Z', hooks:HOOKS, byId:(id)=>HOOKS.find(h=>h.id===id), byName:(n)=>HOOKS.find(h=>h.name===n), byType:(t)=>HOOKS.filter(h=>h.type===t), withSEAM:()=>HOOKS.filter(h=>h.seam!==null), active:()=>HOOKS.filter(h=>h.status==='active') };
