'use strict';
/**
 * contracts/nodes/axioms.node.js — extracted from contracts/SYSTEM-CONTRACTS.js
 * Real node id: contracts.axioms.node
 * §EXTRACTED 2026-09-12 — cli/decompose.js --mode=registry, block AXIOMS.
 * Verbatim body — this extraction moves the const, it does not re-derive it,
 * so nothing about the taxonomy itself changed, only where it lives.
 */
module.exports = Object.freeze({
  '§1.1':  'Nothing exists until proven.',
  '§1.2':  'Nothing silently fails.',
  '§1.3':  'No stubs in production.',
  '§2.1':  'Persistence is the golden rule.',
  '§2.2':  'Storage device is source of truth.',
  '§2.3':  'All state must be observable.',
  '§3.1':  'Bottom-up only.',
  '§3.2':  'Logical time (eventTs) is the ordering axis.',
  '§4.1':  'A system that cannot be tested cannot be trusted.',
  '§4.2':  'Fix bugs pre-emptively.',
  '§4.3':  'Enterprise grade. Military grade security.',
  '§5.1':  'Everything has a UUID, hook, and event bus registration.',
  '§5.2':  'Everything routes through RAID.',
  '§5.3':  'No monkey patches — full system patches only.',
  '§5.4':  'Versions persist across the entire project.',
  '§5.5':  'What does not exist must be built.',
  '§5.6':  'Structural self-similarity (fractal law).',
  '§5.7':  'Low coupling, high cohesion.',
  '§5.8':  'Composability over configuration.',
  '§6.1':  'Documentation is generated from proof.',
  '§6.2':  'Always read before building.',
  '§7.0':  'Event ontology separation.',
  '§7.1':  'Dual ledger architecture.',
  '§7.2':  'Ideas cannot affect runtime.',
  '§7.3':  'Cognition is not history.',
  '§7.4':  'Track methods, solutions, and patterns.',
  '§7.5':  'Classify idea failure.',
  '§7.6':  'Codebase is a materialised view of the Upgrade Ledger.',
  '§7.7':  'Bottleneck detection via ledger flow.',
  '§8.1':  'Begin every session with context.',
  '§8.2':  'Nothing passes the idea gate without hostile review.',
  '§8.3':  'SISO and Jaa are load-order prerequisites.',
  // Session-established rules
  '§RAID-01': 'RAID is the only write authority for requests.',
  '§RAID-02': 'Ledger write before dispatch. Always.',
  '§RAID-03': 'Held requests never leave the queue.',
  '§RAID-04': 'MAX_ROUTE_DEPTH = 3. routeHistory written on every hop.',
  '§IDENTITY-01': 'One UUID per request event. Assigned by Bridge.',
  '§IDENTITY-02': 'One SHA-256 hash per content artifact.',
  '§IDENTITY-03': 'Session UUID chain links prompts within a conversation.',
  '§TRUTH-01': 'Each data type has exactly one write authority.',
  '§TRUTH-02': 'Cortex requests table is a projection, not a source.',
  '§TRUTH-03': 'SESSION.md is a compiled artifact, not a manual document.',
  '§SISO-01':  'Every cross-system feature is a SISO pipeline.',
  '§SISO-02':  'Gates are pure functions.',
  '§SISO-03':  'Signature collision is a hard error.',
  '§SISO-04':  'Infinite loop prevention via wasProcessedBy().',
  '§SISO-05':  'The ledger IS the learning system.',
  '§US-01':    'Userscript kernel/UI separation is mandatory.',
  '§US-02':    'IndexedDB is the userscript persistence layer.',
  '§US-03':    'Replay authority belongs to the userscript kernel.',
  '§US-04':    'Context injection is pre-prompt, not post-response.',
  '§US-05':    'SHA-256 hash dedup replaces simpleHash().',

  // Causal physics axioms
  '§CAUSAL-01': 'Compound analysis is async, gated, and selective. Never universal.',
  '§CAUSAL-02': 'Compound events (compound.*) never re-trigger compound analysis. No recomputation storms.',
  '§CAUSAL-03': 'Ripple/wave/tidal are emergent propagation regimes, not assigned labels.',
  '§CAUSAL-04': 'Every causal record carries the CausalImpulse that drove propagation.',
  '§CAUSAL-05': 'Regime is read FROM propagation physics — not written to it.',
  '§CAUSAL-06': 'The CFR ledger is a causal simulation substrate, not a debugging log.',
  '§CAUSAL-07': 'Every cause is as important as the conditions of its effect.',
});
